### PR TITLE
Update LICENSE to MIT

### LINKED ISSUE #35: Dual License
@jhalterman What are your thoughts on making the project Dual License by adding MIT license? 

A lot of the Go modules are MIT, and the license on this one conflicts with that.

### PR DESCRIPTION
**Pull request by gaby**
Adds support for both MIT and Apache 2.0 License which would allow projects using any of those to use this dependency.

Fixes #35

### CODE REVIEW

**Comment by jhalterman** [comment]
How about we just switch the license to MIT?

**Comment by gaby** [comment]
@jhalterman Dual-licensing MIT/Apache-2.0 gives you a permissive license with a patent grant and GPLv2-compatibility.

https://news.ycombinator.com/item?id=21566968
https://fossa.com/blog/dual-licensing-models-explained/
https://github.com/microsoft/windows-rs/issues/426#issuecomment-765337069

I'm going to do another commt to make it use the template from https://github.com/arnavyc/dual-licensed-mit-apache

**Comment by gaby** [comment]
@jhalterman Updated based on the template. The "OR" means the user can use the library as either Apache 2.0 OR MIT License.

**Comment by jhalterman** [comment]
Yea I'm familiar with dual licensing, but I'd still prefer to just license under one or the other, in which case switching to MIT is fine.

**Comment by gaby** [comment]
@jhalterman Done, updated files

**Review by jhalterman — APPROVED** [review]

**Comment by jhalterman** [comment]
Thanks @gaby

**Pull request merged**
