### PR TITLE
Updates to dependencies, and support for multi-platform CI

### PR DESCRIPTION
**Pull request by gaby**
- Add dependabot for tracking github-actions and go dependencies
- Updated all dependencies to their latest version
- ~Added multi-platform~ tests fail on Windows.
- Make CI ignore changes to license, and .md files

### CODE REVIEW

**Comment by gaby** [comment]
@jhalterman I noticed all the dependencies were outdated, this PR covers updating that and adding dependabot to track future dependency updates.

**Comment by gaby** [comment]
Ping @jhalterman

**Comment by gaby** [comment]
@jhalterman can you take a look at this PR

**Comment by jhalterman** [comment]
@gaby Apologies for the delay. Would you like to reopen this PR?

**Comment by gaby** [comment]
> @gaby Apologies for the delay. Would you like to reopen this PR?

Will open a new one in a few, this branch is gone.

**Pull request closed without merging**
